channel:
     source: youtube-main-default
     name: config learning main default
     url: http://localhost:8080/main-default 

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true  
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      instance: 
      hostname: localhost
