channel:
     source: youtube-main-dev
     name: config learning main dev
     url: http://localhost:8080/main-dev 

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true  
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      instance: 
      hostname: localhost
